## Numpy Functions for Linear 

Let’s start with some basic matrix operations. Suppose we have two matrices, $A$ and $B$, and we want to add them together. In NumPy, we can do this with the simple command, $A+B$. Let’s look into the detailed computational steps.

### Matrix Addition

In [4]:
# Addition and Subtraction
import numpy as np
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
print(matrix1 + matrix2) # prints [[6, 8], [10, 12]]

[[ 6  8]
 [10 12]]


In [6]:
C=2*matrix1+5*matrix2+np.dot(matrix1,matrix2)
print("Output of the matrix operation\n")
print(C)

Output of the matrix operation

[[46 56]
 [84 98]]


### Matrix subtraction
Similary, matrix difference and other matrix operations can be illustrated as follows.



In [7]:
print(matrix1 - matrix2) # prints [[-4, -4], [-4, -4]]

[[-4 -4]
 [-4 -4]]


>**Tasks:**

1. Evaluate `M=5 matrix1-7 matrix2`
2. Evaluate `M2=5 matrix1-7I`

In [14]:
M=5*matrix1-7*matrix2
M2=5*matrix1-7*np.eye(2)
print("M\n:",M)
print("\nM2",M2)

M
: [[-30 -32]
 [-34 -36]]

M2 [[-2. 10.]
 [15. 13.]]


### Scalar Multiplication

In [15]:
# Scalar Multiplication
matrix = np.array([[1, 2], [3, 4]])
print(2 * matrix) # prints [[2, 4], [6, 8]]

[[2 4]
 [6 8]]


>**Task:1**

1. Create a random $5\times 5$ matrix and find $T_1=5A-3I$.

In [18]:
A=np.array([[1,2,3 ,4, 5],[2,3,4,5,6],[2,3,4,5,6],[2,3,4,5,6],[2,3,4,5,6]])
T1=5*A-3*np.eye(5)
print(T1)

[[ 2. 10. 15. 20. 25.]
 [10. 12. 20. 25. 30.]
 [10. 15. 17. 25. 30.]
 [10. 15. 20. 22. 30.]
 [10. 15. 20. 25. 27.]]


### Matrix Multiplication


In [19]:
# Matrix Multiplication
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
print(np.dot(matrix1, matrix2)) # prints [[19, 22], [43, 50]]

[[19 22]
 [43 50]]


:::{.callout-note}
## Note:

Norm: The norm of a vector is a scalar that represents the “length” of the vector. In NumPy, we can compute the norm using the numpy.linalg.norm function. The inner product of two vectors is a matrix that is computed by multiplying the first vector by the transpose of the second vector. In NumPy, we can compute the inner product using the numpy.inner function.

:::

In [20]:
# finding norm
vector = np.array([1, 2, 3])
print(np.linalg.norm(vector)) # prints 3.74165738677

3.7416573867739413
