## Introduction to `NumPy`

In [2]:
# loading library
import numpy as np

## Working with arrays

In [3]:
A=np.array([[1,2,5],[6,9,8],[1,1,3]])
print(A)

[[1 2 5]
 [6 9 8]
 [1 1 3]]


In [4]:
A.shape

(3, 3)

>**Tasks:**
1. Create a one dimensional array using `Numpy`
2. Create a $2\times 3$ matrix, $B=\begin{pmatrix} 1&3&8\\ 2&4&5\end{pmatrix}$

**Solution:**

In [11]:
# creating one dimensional array
A=np.array([1,2,3])
print("The array is:",A)
print("Shape of A is :",A.shape)

The array is: [1 2 3]
Shape of A is : (3,)


>**Note:** It is important to note that, `np.array([1,2,3])` creates an array but `np.array([[1,2,3]])` creates a matrix of size `(1,3)`.

In [13]:
# create the 2X3 matrix B
B=np.array([[1,3,8],[2,4,5]])
print("The matrix is:\n", B)
print("Shape of B:",B.shape)

The matrix is:
 [[1 3 8]
 [2 4 5]]
Shape of B: (2, 3)


## Different types of matrices

1. *Zeror matrix*

A zero matrix of size $m\times n$ can be created using the syntax: `np.zeros((m,n))`. For example, a $2\times 5$ zero matrix can be created as follows.

In [14]:
Z=np.zeros((2,5))
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


2. *One matrix*

A matrix will all entries as 1, is called a one matrix. Syntax: `np.ones((m,n))`. Example of one matrix is given below.

In [15]:
np.ones((3,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])